mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
proxies:
- name: Svaston_vpn_3a4cd9__3a4cd922
  server: 185.147.26.210
  port: 443
  type: vless
  uuid: 1c5ed2e1-56da-41ab-9a78-159d9892ec17
  udp: true
  flow: xtls-rprx-vision
  tls: true
  server-name: example.com
  skip-cert-verify: false
  reality-opts:
    public-key: 9rdvkUGJyNbRvsB0Pp06h1URq9AHDPRtH9-wmNB1-j4
- name: Svaston_vpn_3ecb5a__3ecb5a06
  server: 193.187.95.124
  port: 443
  type: vless
  uuid: 81167507-b634-4f56-9555-33e4fd660ce0
  udp: true
  flow: ''
  tls: true
  server-name: github.com
  skip-cert-verify: false
  reality-opts:
    public-key: 8bMoXjt19DiBhVEEzx2xxe9dsgYOerlQC6yf0JDOoQE
- name: Svaston_vpn_675dad__675dad23
  server: 198.100.154.175
  port: 2087
  type: vless
  uuid: 97ea73b6-2043-4238-903c-a1e3d4a43c96
  udp: true
  flow: ''
  network: ws
  tls: true
  server-name: amphetamine.adaspoloandco.com
  skip-cert-verify: false
  ws-opts:
    path: /download.php
    headers:
      Host: 198.100.154.175
- name: Svaston_vpn_85d2d1__85d2d12c
  server: 200.165.231.209
  port: 443
  type: vless
  uuid: ff0b6ba8-bed0-4c4d-bbc9-23af47582615
  udp: true
  flow: ''
  network: ws
  tls: true
  server-name: wstg.datasynctrue.online
  skip-cert-verify: false
  ws-opts:
    path: /api/connect
    headers:
      Host: wstg.datasynctrue.online
- name: Svaston_vpn_54a9b9__54a9b919
  server: 31.58.178.110
  port: 443
  type: vless
  uuid: 87fd990d-ca93-440a-bbd4-e8281c4a0910
  udp: true
  flow: xtls-rprx-vision
  tls: true
  server-name: de3.swcdn.xyz
  skip-cert-verify: false
  reality-opts:
    public-key: N6RFNy2oUKtxhdpKyIbZnjWSMghyiu37veqd6MLjbgk
- name: Svaston_vpn_0c0f56__0c0f561d
  server: 31.59.206.218
  port: 443
  type: vless
  uuid: 87fd990d-ca93-440a-bbd4-e8281c4a0910
  udp: true
  flow: xtls-rprx-vision
  tls: true
  server-name: pl3.cloud-static.org
  skip-cert-verify: false
  reality-opts:
    public-key: cIgH-cz8JCjHnPQXA4qZNpYWwgYdVKCX3jDhuDbVK24
- name: Svaston_vpn_cd38e2__cd38e2f0
  server: 5.157.10.250
  port: 443
  type: vless
  uuid: c20751de-06c3-4044-b6a4-eebc9b040d92
  udp: true
  flow: xtls-rprx-vision
  tls: true
  server-name: swebz.loozerp.wiki
  skip-cert-verify: false
  reality-opts:
    public-key: pgG2grngQEtOFJImLfz0AEm-O2IodM2jCY4aMCYQI1U
- name: Svaston_vpn_587479__5874798a
  server: 62.105.220.106
  port: 443
  type: vless
  uuid: 30e52776-55ac-3cb4-8d36-e2910f07e2c3
  udp: true
  flow: xtls-rprx-vision
  tls: true
  server-name: u695098u7dae9c0cs220.gogocs.xyz
  skip-cert-verify: false
- name: Svaston_vpn_66d5bb__66d5bb6b
  server: du-rov.secureservice.top
  port: 8443
  type: vless
  uuid: c53ea5e9-ed8b-4990-805d-7f1d6451426c
  udp: true
  flow: xtls-rprx-vision
  tls: true
  server-name: du-rov.secureservice.top
  skip-cert-verify: false
  reality-opts:
    public-key: fSVfR9NB-6J6smrZlavi0GWd8JfDh0aXuEkKbtuFzUI
- name: Svaston_vpn_f83dd1__f83dd1c3
  server: iiproxy88.iiproxy.com
  port: 8443
  type: vless
  uuid: 806fa224-44f7-4c1b-b7a3-05bfdfdfbf87
  udp: true
  flow: ''
  network: ws
  tls: true
  server-name: iiproxy88.iiproxy.com
  skip-cert-verify: false
  ws-opts:
    path: /
    headers:
      Host: iiproxy88.iiproxy.com
- name: Svaston_vpn_553d56__553d5635
  server: s3.bamans.uk
  port: 443
  type: vless
  uuid: 86c0996e-817e-409f-a732-ff9ef94917bd
  udp: true
  flow: ''
  network: xhttp
  tls: true
  server-name: s3.bamans.uk
  skip-cert-verify: false
- name: Svaston_vpn_5f902d__5f902d68
  server: 18.176.61.69
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_543ced__543ced8a
  server: 54.65.177.190
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_2d63a4__2d63a49a
  server: fancy-javelin.rooster465.autos
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_e7e0de__e7e0de02
  server: integral-rodent.rooster465.autos
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_976a13__976a1359
  server: liked-eft.rooster465.autos
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_d9c29d__d9c29d71
  server: obliging-louse.rooster465.autos
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_71dc4c__71dc4c95
  server: promoted-rattler.rooster465.autos
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_8c7fc3__8c7fc329
  server: real-cardinal.rooster465.autos
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_32cf28__32cf28ae
  server: 8.217.254.88
  port: 443
  type: vmess
  uuid: f23bb427c1f94373876c2f43e9f790f3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  tls: true
  server-name: 2b9hwy8ocx7q74nm.v.3dns.vip
  skip-cert-verify: false
  ws-opts:
    path: /ws-vmess
    headers:
      Host: 2b9hwY8oCx7Q74NM.v.3dns.vip
- name: Svaston_vpn_c1407c__c1407ca2
  server: guanwang.awsno.com
  port: 443
  type: vmess
  uuid: 6a89a215-22bf-4bd7-9642-b95b2e09583a
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  tls: true
  server-name: guanwang.awsno.com
  skip-cert-verify: false
  ws-opts:
    path: /hls/cctv5phd.m3u8
    headers:
      Host: guanwang.awsno.com
- name: Svaston_vpn_d1bff5__d1bff5d1
  server: 152.32.254.68
  port: 5010
  type: hysteria2
  password: ''
  server-name: 127.0.0.1
  skip-cert-verify: true
- name: Svaston_vpn_ede402__ede40247
  server: 31.76.71.233
  port: 443
  type: hysteria2
  password: ''
  server-name: info.wwwinternetvideo.click
  skip-cert-verify: false
- name: Svaston_vpn_fe0a14__fe0a14ef
  server: i.wareznet.ru
  port: 8446
  type: hysteria2
  password: ''
  server-name: i.wareznet.ru
  skip-cert-verify: false
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - Svaston_vpn_3a4cd9__3a4cd922
  - Svaston_vpn_3ecb5a__3ecb5a06
  - Svaston_vpn_675dad__675dad23
  - Svaston_vpn_85d2d1__85d2d12c
  - Svaston_vpn_54a9b9__54a9b919
  - Svaston_vpn_0c0f56__0c0f561d
  - Svaston_vpn_cd38e2__cd38e2f0
  - Svaston_vpn_587479__5874798a
  - Svaston_vpn_66d5bb__66d5bb6b
  - Svaston_vpn_f83dd1__f83dd1c3
  - Svaston_vpn_553d56__553d5635
  - Svaston_vpn_5f902d__5f902d68
  - Svaston_vpn_543ced__543ced8a
  - Svaston_vpn_2d63a4__2d63a49a
  - Svaston_vpn_e7e0de__e7e0de02
  - Svaston_vpn_976a13__976a1359
  - Svaston_vpn_d9c29d__d9c29d71
  - Svaston_vpn_71dc4c__71dc4c95
  - Svaston_vpn_8c7fc3__8c7fc329
  - Svaston_vpn_32cf28__32cf28ae
  - Svaston_vpn_c1407c__c1407ca2
  - Svaston_vpn_d1bff5__d1bff5d1
  - Svaston_vpn_ede402__ede40247
  - Svaston_vpn_fe0a14__fe0a14ef
  - DIRECT
- name: AUTO
  type: url-test
  proxies:
  - Svaston_vpn_3a4cd9__3a4cd922
  - Svaston_vpn_3ecb5a__3ecb5a06
  - Svaston_vpn_675dad__675dad23
  - Svaston_vpn_85d2d1__85d2d12c
  - Svaston_vpn_54a9b9__54a9b919
  - Svaston_vpn_0c0f56__0c0f561d
  - Svaston_vpn_cd38e2__cd38e2f0
  - Svaston_vpn_587479__5874798a
  - Svaston_vpn_66d5bb__66d5bb6b
  - Svaston_vpn_f83dd1__f83dd1c3
  - Svaston_vpn_553d56__553d5635
  - Svaston_vpn_5f902d__5f902d68
  - Svaston_vpn_543ced__543ced8a
  - Svaston_vpn_2d63a4__2d63a49a
  - Svaston_vpn_e7e0de__e7e0de02
  - Svaston_vpn_976a13__976a1359
  - Svaston_vpn_d9c29d__d9c29d71
  - Svaston_vpn_71dc4c__71dc4c95
  - Svaston_vpn_8c7fc3__8c7fc329
  - Svaston_vpn_32cf28__32cf28ae
  - Svaston_vpn_c1407c__c1407ca2
  - Svaston_vpn_d1bff5__d1bff5d1
  - Svaston_vpn_ede402__ede40247
  - Svaston_vpn_fe0a14__fe0a14ef
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
rules:
- MATCH,PROXY
