mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
proxies:
- name: Svaston_vpn_53ced0__53ced080
  server: 34.220.15.24
  port: 443
  type: trojan
  password: UX82473651
  udp: true
- name: Svaston_vpn_184a46__184a46c6
  server: 44.255.123.205
  port: 443
  type: trojan
  password: UX82473651
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - Svaston_vpn_53ced0__53ced080
  - Svaston_vpn_184a46__184a46c6
  - DIRECT
- name: AUTO
  type: url-test
  proxies:
  - Svaston_vpn_53ced0__53ced080
  - Svaston_vpn_184a46__184a46c6
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
rules:
- MATCH,PROXY
